/* Generated by Yosys 0.67+4 (git sha1 b88b73a99-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin23.5-clang++ 18.1.8) */

module crc8(clk, rst, data_valid, data_in, crc_out);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input data_valid;
  wire data_valid;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] crc_out;
  wire [7:0] crc_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire [7:0] c;
  wire [7:0] d;
  INV _077_ (
    .I(data_valid),
    .O(_011_)
  );
  INV _078_ (
    .I(crc_out[5]),
    .O(_012_)
  );
  INV _079_ (
    .I(rst),
    .O(_013_)
  );
  INV _080_ (
    .I(data_in[4]),
    .O(_014_)
  );
  XOR _081_ (
    .I0(crc_out[5]),
    .I1(crc_out[6]),
    .O(_015_)
  );
  XOR _082_ (
    .I0(data_in[6]),
    .I1(data_in[5]),
    .O(_016_)
  );
  XOR _083_ (
    .I0(crc_out[4]),
    .I1(data_in[4]),
    .O(_017_)
  );
  XOR _084_ (
    .I0(_015_),
    .I1(_017_),
    .O(_018_)
  );
  XOR _085_ (
    .I0(_016_),
    .I1(_018_),
    .O(_019_)
  );
  OR2 _086_ (
    .I0(_011_),
    .I1(_019_),
    .O(_020_)
  );
  OR2 _087_ (
    .I0(data_valid),
    .I1(crc_out[6]),
    .O(_021_)
  );
  AND2 _088_ (
    .I0(_013_),
    .I1(_021_),
    .O(_022_)
  );
  AND2 _089_ (
    .I0(_020_),
    .I1(_022_),
    .O(_000_)
  );
  XOR _090_ (
    .I0(data_in[5]),
    .I1(data_in[3]),
    .O(_023_)
  );
  XOR _091_ (
    .I0(_014_),
    .I1(_023_),
    .O(_024_)
  );
  XOR _092_ (
    .I0(crc_out[3]),
    .I1(crc_out[4]),
    .O(_025_)
  );
  INV _093_ (
    .I(_025_),
    .O(_026_)
  );
  XOR _094_ (
    .I0(_024_),
    .I1(_026_),
    .O(_027_)
  );
  XOR _095_ (
    .I0(_024_),
    .I1(_025_),
    .O(_028_)
  );
  AND2 _096_ (
    .I0(data_valid),
    .I1(_027_),
    .O(_029_)
  );
  OR2 _097_ (
    .I0(_011_),
    .I1(_028_),
    .O(_030_)
  );
  OR2 _098_ (
    .I0(_012_),
    .I1(_030_),
    .O(_031_)
  );
  OR2 _099_ (
    .I0(crc_out[5]),
    .I1(_029_),
    .O(_032_)
  );
  AND2 _100_ (
    .I0(_013_),
    .I1(_032_),
    .O(_033_)
  );
  AND2 _101_ (
    .I0(_031_),
    .I1(_033_),
    .O(_001_)
  );
  XOR _102_ (
    .I0(data_in[4]),
    .I1(data_in[2]),
    .O(_034_)
  );
  XOR _103_ (
    .I0(_025_),
    .I1(_034_),
    .O(_035_)
  );
  XOR _104_ (
    .I0(crc_out[2]),
    .I1(data_in[3]),
    .O(_036_)
  );
  XOR _105_ (
    .I0(_035_),
    .I1(_036_),
    .O(_037_)
  );
  OR2 _106_ (
    .I0(_011_),
    .I1(_037_),
    .O(_038_)
  );
  OR2 _107_ (
    .I0(data_valid),
    .I1(crc_out[4]),
    .O(_039_)
  );
  AND2 _108_ (
    .I0(_013_),
    .I1(_039_),
    .O(_040_)
  );
  AND2 _109_ (
    .I0(_038_),
    .I1(_040_),
    .O(_002_)
  );
  XOR _110_ (
    .I0(crc_out[2]),
    .I1(data_in[1]),
    .O(_041_)
  );
  XOR _111_ (
    .I0(crc_out[3]),
    .I1(_041_),
    .O(_042_)
  );
  XOR _112_ (
    .I0(crc_out[1]),
    .I1(data_in[7]),
    .O(_043_)
  );
  XOR _113_ (
    .I0(data_in[3]),
    .I1(_043_),
    .O(_044_)
  );
  XOR _114_ (
    .I0(crc_out[7]),
    .I1(data_in[2]),
    .O(_045_)
  );
  XOR _115_ (
    .I0(_044_),
    .I1(_045_),
    .O(_046_)
  );
  XOR _116_ (
    .I0(_042_),
    .I1(_046_),
    .O(_047_)
  );
  OR2 _117_ (
    .I0(_011_),
    .I1(_047_),
    .O(_048_)
  );
  OR2 _118_ (
    .I0(data_valid),
    .I1(crc_out[3]),
    .O(_049_)
  );
  AND2 _119_ (
    .I0(_013_),
    .I1(_049_),
    .O(_050_)
  );
  AND2 _120_ (
    .I0(_048_),
    .I1(_050_),
    .O(_003_)
  );
  XOR _121_ (
    .I0(data_in[6]),
    .I1(data_in[2]),
    .O(_051_)
  );
  XOR _122_ (
    .I0(crc_out[2]),
    .I1(crc_out[6]),
    .O(_052_)
  );
  XOR _123_ (
    .I0(_051_),
    .I1(_052_),
    .O(_053_)
  );
  XOR _124_ (
    .I0(crc_out[0]),
    .I1(crc_out[1]),
    .O(_054_)
  );
  XOR _125_ (
    .I0(data_in[1]),
    .I1(data_in[0]),
    .O(_055_)
  );
  XOR _126_ (
    .I0(_054_),
    .I1(_055_),
    .O(_056_)
  );
  XOR _127_ (
    .I0(_053_),
    .I1(_056_),
    .O(_057_)
  );
  OR2 _128_ (
    .I0(_011_),
    .I1(_057_),
    .O(_058_)
  );
  OR2 _129_ (
    .I0(data_valid),
    .I1(crc_out[2]),
    .O(_059_)
  );
  AND2 _130_ (
    .I0(_013_),
    .I1(_059_),
    .O(_060_)
  );
  AND2 _131_ (
    .I0(_058_),
    .I1(_060_),
    .O(_004_)
  );
  XOR _132_ (
    .I0(crc_out[6]),
    .I1(data_in[6]),
    .O(_061_)
  );
  XOR _133_ (
    .I0(_056_),
    .I1(_061_),
    .O(_062_)
  );
  OR2 _134_ (
    .I0(_011_),
    .I1(_062_),
    .O(_063_)
  );
  OR2 _135_ (
    .I0(data_valid),
    .I1(crc_out[1]),
    .O(_064_)
  );
  AND2 _136_ (
    .I0(_013_),
    .I1(_064_),
    .O(_065_)
  );
  AND2 _137_ (
    .I0(_063_),
    .I1(_065_),
    .O(_005_)
  );
  XOR _138_ (
    .I0(data_in[7]),
    .I1(data_in[0]),
    .O(_066_)
  );
  XOR _139_ (
    .I0(crc_out[7]),
    .I1(_066_),
    .O(_067_)
  );
  XOR _140_ (
    .I0(crc_out[0]),
    .I1(_061_),
    .O(_068_)
  );
  XOR _141_ (
    .I0(_067_),
    .I1(_068_),
    .O(_069_)
  );
  OR2 _142_ (
    .I0(_011_),
    .I1(_069_),
    .O(_070_)
  );
  OR2 _143_ (
    .I0(data_valid),
    .I1(crc_out[0]),
    .O(_071_)
  );
  AND2 _144_ (
    .I0(_013_),
    .I1(_071_),
    .O(_072_)
  );
  AND2 _145_ (
    .I0(_070_),
    .I1(_072_),
    .O(_006_)
  );
  XOR _146_ (
    .I0(data_in[7]),
    .I1(_016_),
    .O(_073_)
  );
  XOR _147_ (
    .I0(_015_),
    .I1(_073_),
    .O(_074_)
  );
  AND2 _148_ (
    .I0(data_valid),
    .I1(_074_),
    .O(_075_)
  );
  AND2 _149_ (
    .I0(crc_out[7]),
    .I1(_075_),
    .O(_076_)
  );
  INV _150_ (
    .I(_076_),
    .O(_008_)
  );
  OR2 _151_ (
    .I0(crc_out[7]),
    .I1(_075_),
    .O(_009_)
  );
  AND2 _152_ (
    .I0(_013_),
    .I1(_009_),
    .O(_010_)
  );
  AND2 _153_ (
    .I0(_008_),
    .I1(_010_),
    .O(_007_)
  );
  FF _154_ (
    .C(clk),
    .D(_006_),
    .Q(crc_out[0])
  );
  FF _155_ (
    .C(clk),
    .D(_005_),
    .Q(crc_out[1])
  );
  FF _156_ (
    .C(clk),
    .D(_004_),
    .Q(crc_out[2])
  );
  FF _157_ (
    .C(clk),
    .D(_003_),
    .Q(crc_out[3])
  );
  FF _158_ (
    .C(clk),
    .D(_002_),
    .Q(crc_out[4])
  );
  FF _159_ (
    .C(clk),
    .D(_001_),
    .Q(crc_out[5])
  );
  FF _160_ (
    .C(clk),
    .D(_000_),
    .Q(crc_out[6])
  );
  FF _161_ (
    .C(clk),
    .D(_007_),
    .Q(crc_out[7])
  );
  assign c = crc_out;
  assign d = data_in;
endmodule
