/* Generated by Yosys 0.67+4 (git sha1 b88b73a99-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin23.5-clang++ 18.1.8) */

module fifo(clk, rst, wr_en, rd_en, din, dout, full, empty);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input wr_en;
  wire wr_en;
  input rd_en;
  wire rd_en;
  input [7:0] din;
  wire [7:0] din;
  output [7:0] dout;
  reg [7:0] dout;
  output full;
  wire full;
  output empty;
  wire empty;
  wire [3:0] _00_;
  wire [7:0] _01_;
  wire [7:0] _02_;
  wire [7:0] _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire [7:0] _23_;
  wire [31:0] _24_;
  wire [31:0] _25_;
  wire [31:0] _26_;
  wire [31:0] _27_;
  reg [4:0] rd_ptr;
  reg [4:0] wr_ptr;
  reg [7:0] mem [15:0];
  always @(posedge clk) begin
    if (_02_[0])
      mem[_00_] <= _01_;
  end
  assign _23_ = mem[rd_ptr[3:0]];
  assign _24_[0] = ~wr_ptr[0];
  assign _26_[0] = ~rd_ptr[0];
  assign _05_ = ~rst;
  assign _06_ = rd_ptr[0] & rd_ptr[1];
  assign _07_ = rd_ptr[2] & _06_;
  assign _08_ = rd_ptr[3] & _07_;
  assign _27_[3] = rd_ptr[3] ^ _07_;
  assign _27_[4] = rd_ptr[4] ^ _08_;
  assign _09_ = wr_ptr[1] ^ rd_ptr[1];
  assign _10_ = wr_ptr[0] ^ rd_ptr[0];
  assign _11_ = _09_ | _10_;
  assign _12_ = rd_ptr[2] ^ wr_ptr[2];
  assign _13_ = rd_ptr[3] ^ wr_ptr[3];
  assign _14_ = _12_ | _13_;
  assign _15_ = _11_ | _14_;
  assign _16_ = rd_ptr[4] ^ wr_ptr[4];
  assign _17_ = ~_16_;
  assign _18_ = _15_ | _17_;
  assign full = ~_18_;
  assign _03_[0] = wr_en & _18_;
  assign _02_[0] = _05_ & _03_[0];
  assign _00_[2] = wr_ptr[2] & _02_[0];
  assign _00_[1] = wr_ptr[1] & _02_[0];
  assign _00_[0] = wr_ptr[0] & _02_[0];
  assign _01_[6] = din[6] & _02_[0];
  assign _01_[5] = din[5] & _02_[0];
  assign _01_[4] = din[4] & _02_[0];
  assign _01_[3] = din[3] & _02_[0];
  assign _01_[2] = din[2] & _02_[0];
  assign _01_[1] = din[1] & _02_[0];
  assign _01_[0] = din[0] & _02_[0];
  assign _19_ = wr_ptr[1] & wr_ptr[0];
  assign _20_ = wr_ptr[2] & _19_;
  assign _21_ = wr_ptr[3] & _20_;
  assign _25_[3] = wr_ptr[3] ^ _20_;
  assign _25_[2] = wr_ptr[2] ^ _19_;
  assign _25_[1] = wr_ptr[1] ^ wr_ptr[0];
  assign _00_[3] = wr_ptr[3] & _02_[0];
  assign _01_[7] = din[7] & _02_[0];
  assign _27_[2] = rd_ptr[2] ^ _06_;
  assign _22_ = _15_ | _16_;
  assign empty = ~_22_;
  assign _04_ = rd_en & _22_;
  assign _25_[4] = wr_ptr[4] ^ _21_;
  assign _27_[1] = rd_ptr[0] ^ rd_ptr[1];
  always @(posedge clk)
    if (rst) rd_ptr[0] <= 1'h0;
    else if (_04_) rd_ptr[0] <= _26_[0];
  always @(posedge clk)
    if (rst) rd_ptr[1] <= 1'h0;
    else if (_04_) rd_ptr[1] <= _27_[1];
  always @(posedge clk)
    if (rst) rd_ptr[2] <= 1'h0;
    else if (_04_) rd_ptr[2] <= _27_[2];
  always @(posedge clk)
    if (rst) rd_ptr[3] <= 1'h0;
    else if (_04_) rd_ptr[3] <= _27_[3];
  always @(posedge clk)
    if (rst) rd_ptr[4] <= 1'h0;
    else if (_04_) rd_ptr[4] <= _27_[4];
  always @(posedge clk)
    if (rst) wr_ptr[0] <= 1'h0;
    else if (_03_[0]) wr_ptr[0] <= _24_[0];
  always @(posedge clk)
    if (rst) wr_ptr[1] <= 1'h0;
    else if (_03_[0]) wr_ptr[1] <= _25_[1];
  always @(posedge clk)
    if (rst) wr_ptr[2] <= 1'h0;
    else if (_03_[0]) wr_ptr[2] <= _25_[2];
  always @(posedge clk)
    if (rst) wr_ptr[3] <= 1'h0;
    else if (_03_[0]) wr_ptr[3] <= _25_[3];
  always @(posedge clk)
    if (rst) wr_ptr[4] <= 1'h0;
    else if (_03_[0]) wr_ptr[4] <= _25_[4];
  always @(posedge clk)
    if (rst) dout[0] <= 1'h0;
    else if (_04_) dout[0] <= _23_[0];
  always @(posedge clk)
    if (rst) dout[1] <= 1'h0;
    else if (_04_) dout[1] <= _23_[1];
  always @(posedge clk)
    if (rst) dout[2] <= 1'h0;
    else if (_04_) dout[2] <= _23_[2];
  always @(posedge clk)
    if (rst) dout[3] <= 1'h0;
    else if (_04_) dout[3] <= _23_[3];
  always @(posedge clk)
    if (rst) dout[4] <= 1'h0;
    else if (_04_) dout[4] <= _23_[4];
  always @(posedge clk)
    if (rst) dout[5] <= 1'h0;
    else if (_04_) dout[5] <= _23_[5];
  always @(posedge clk)
    if (rst) dout[6] <= 1'h0;
    else if (_04_) dout[6] <= _23_[6];
  always @(posedge clk)
    if (rst) dout[7] <= 1'h0;
    else if (_04_) dout[7] <= _23_[7];
  assign _26_[31:1] = { 27'h0000000, rd_ptr[4:1] };
  assign _02_[7:1] = { _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0], _02_[0] };
  assign { _25_[31:6], _25_[0] } = { 26'h0000000, _24_[0] };
  assign { _27_[31:6], _27_[0] } = { 26'h0000000, _26_[0] };
  assign _03_[7:1] = { _03_[0], _03_[0], _03_[0], _03_[0], _03_[0], _03_[0], _03_[0] };
  assign _24_[31:1] = { 27'h0000000, wr_ptr[4:1] };
endmodule
