/* Generated by Yosys 0.67+4 (git sha1 b88b73a99-dirty, Release, Clang /usr/local/osxcross/target/bin/aarch64-apple-darwin23.5-clang++ 18.1.8) */

module uart_tx(clk, rst, tx_start, tx_data, tx_serial, tx_busy, tx_done);
  input clk;
  wire clk;
  input rst;
  wire rst;
  input tx_start;
  wire tx_start;
  input [7:0] tx_data;
  wire [7:0] tx_data;
  output tx_serial;
  reg tx_serial;
  output tx_busy;
  reg tx_busy;
  output tx_done;
  reg tx_done;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire [31:0] _095_;
  reg [2:0] bit_index;
  reg [7:0] clk_count;
  reg [2:0] state;
  reg [7:0] tx_shift;
  assign _039_ = ~bit_index[0];
  assign _040_ = ~bit_index[2];
  assign _001_ = ~state[2];
  assign _041_ = ~state[1];
  assign _042_ = ~state[0];
  assign _043_ = ~clk_count[0];
  assign _044_ = ~bit_index[1];
  assign _045_ = ~rst;
  assign _046_ = bit_index[0] & bit_index[1];
  assign _047_ = bit_index[2] & _046_;
  assign _048_ = ~_047_;
  assign _049_ = clk_count[2] & clk_count[1];
  assign _050_ = clk_count[3] | _049_;
  assign _051_ = clk_count[4] & _050_;
  assign _052_ = clk_count[5] | _051_;
  assign _053_ = clk_count[6] & _052_;
  assign _095_[7] = clk_count[7] | _053_;
  assign _054_ = ~_095_[7];
  assign _055_ = state[2] | _041_;
  assign _056_ = _001_ & _042_;
  assign _057_ = state[1] & _056_;
  assign _058_ = state[0] | _055_;
  assign _059_ = _095_[7] & _057_;
  assign _060_ = _047_ & _059_;
  assign _061_ = _001_ & state[0];
  assign _062_ = _041_ & _061_;
  assign _063_ = _095_[7] & _062_;
  assign _092_ = _060_ | _063_;
  assign _064_ = _041_ & _056_;
  assign _065_ = ~_064_;
  assign _094_ = tx_start & _064_;
  assign _091_ = _060_ | _094_;
  assign _066_ = _042_ ? _055_ : state[2];
  assign _067_ = _057_ | _061_;
  assign _068_ = _054_ & _067_;
  assign _069_ = _095_[7] | _066_;
  assign _070_ = clk_count[0] & clk_count[1];
  assign _071_ = clk_count[2] & _070_;
  assign _072_ = clk_count[3] & _071_;
  assign _073_ = clk_count[4] & _072_;
  assign _074_ = clk_count[5] & _073_;
  assign _075_ = clk_count[6] ^ _074_;
  assign _090_ = _068_ & _075_;
  assign _076_ = clk_count[5] ^ _073_;
  assign _089_ = _068_ & _076_;
  assign _077_ = clk_count[4] ^ _072_;
  assign _088_ = _068_ & _077_;
  assign _078_ = clk_count[3] ^ _071_;
  assign _087_ = _068_ & _078_;
  assign _079_ = clk_count[2] ^ _070_;
  assign _086_ = _068_ & _079_;
  assign _007_ = clk_count[0] ^ clk_count[1];
  assign _085_ = _068_ & _007_;
  assign _084_ = _043_ & _068_;
  assign _008_ = bit_index[0] ^ bit_index[1];
  assign _082_ = _059_ & _008_;
  assign _081_ = _039_ & _059_;
  assign _003_ = _045_ & _094_;
  assign _009_ = _095_[7] | _058_;
  assign _002_ = _056_ & _009_;
  assign _010_ = state[1] & _061_;
  assign _011_ = ~_010_;
  assign _006_ = rst | _011_;
  assign _093_ = _095_[7] & _010_;
  assign _004_ = _064_ | _093_;
  assign _012_ = bit_index[2] | _046_;
  assign _013_ = _048_ & _057_;
  assign _014_ = _047_ | _058_;
  assign _015_ = _012_ & _013_;
  assign _083_ = _095_[7] & _015_;
  assign _016_ = tx_shift[3] & _040_;
  assign _017_ = bit_index[2] & tx_shift[7];
  assign _018_ = _044_ | _017_;
  assign _019_ = _016_ | _018_;
  assign _020_ = _040_ & tx_shift[1];
  assign _021_ = bit_index[2] & tx_shift[5];
  assign _022_ = bit_index[1] | _021_;
  assign _023_ = _020_ | _022_;
  assign _024_ = _019_ & _023_;
  assign _025_ = _040_ & tx_shift[0];
  assign _026_ = bit_index[2] & tx_shift[4];
  assign _027_ = bit_index[1] | _026_;
  assign _028_ = _025_ | _027_;
  assign _029_ = tx_shift[2] & _040_;
  assign _030_ = bit_index[2] & tx_shift[6];
  assign _031_ = _044_ | _030_;
  assign _032_ = _029_ | _031_;
  assign _033_ = _028_ & _032_;
  assign _034_ = _039_ ? _033_ : _024_;
  assign _035_ = _041_ | _034_;
  assign _036_ = _056_ & _035_;
  assign _080_ = _010_ | _036_;
  assign _037_ = tx_start | _065_;
  assign _038_ = _014_ & _037_;
  assign _005_ = _069_ & _038_;
  assign _000_ = ~state[2];
  always @(posedge clk)
    if (rst) clk_count[0] <= 1'h0;
    else if (_001_) clk_count[0] <= _084_;
  always @(posedge clk)
    if (rst) clk_count[1] <= 1'h0;
    else if (_001_) clk_count[1] <= _085_;
  always @(posedge clk)
    if (rst) clk_count[2] <= 1'h0;
    else if (_001_) clk_count[2] <= _086_;
  always @(posedge clk)
    if (rst) clk_count[3] <= 1'h0;
    else if (_001_) clk_count[3] <= _087_;
  always @(posedge clk)
    if (rst) clk_count[4] <= 1'h0;
    else if (_001_) clk_count[4] <= _088_;
  always @(posedge clk)
    if (rst) clk_count[5] <= 1'h0;
    else if (_001_) clk_count[5] <= _089_;
  always @(posedge clk)
    if (rst) clk_count[6] <= 1'h0;
    else if (_001_) clk_count[6] <= _090_;
  always @(posedge clk)
    if (rst) clk_count[7] <= 1'h0;
    else if (_001_) clk_count[7] <= 1'h0;
  always @(posedge clk)
    if (rst) state[0] <= 1'h0;
    else if (_005_) state[0] <= _091_;
  always @(posedge clk)
    if (rst) state[1] <= 1'h0;
    else if (_005_) state[1] <= _092_;
  always @(posedge clk)
    if (rst) state[2] <= 1'h0;
    else if (_005_) state[2] <= _093_;
  always @(posedge clk)
    if (_006_) tx_done <= 1'h0;
    else tx_done <= _095_[7];
  always @(posedge clk)
    if (rst) tx_busy <= 1'h0;
    else if (_004_) tx_busy <= _094_;
  always @(posedge clk)
    if (rst) tx_serial <= 1'h1;
    else if (_000_) tx_serial <= _080_;
  always @(posedge clk)
    if (_003_) tx_shift[0] <= tx_data[0];
  always @(posedge clk)
    if (_003_) tx_shift[1] <= tx_data[1];
  always @(posedge clk)
    if (_003_) tx_shift[2] <= tx_data[2];
  always @(posedge clk)
    if (_003_) tx_shift[3] <= tx_data[3];
  always @(posedge clk)
    if (_003_) tx_shift[4] <= tx_data[4];
  always @(posedge clk)
    if (_003_) tx_shift[5] <= tx_data[5];
  always @(posedge clk)
    if (_003_) tx_shift[6] <= tx_data[6];
  always @(posedge clk)
    if (_003_) tx_shift[7] <= tx_data[7];
  always @(posedge clk)
    if (rst) bit_index[0] <= 1'h0;
    else if (_002_) bit_index[0] <= _081_;
  always @(posedge clk)
    if (rst) bit_index[1] <= 1'h0;
    else if (_002_) bit_index[1] <= _082_;
  always @(posedge clk)
    if (rst) bit_index[2] <= 1'h0;
    else if (_002_) bit_index[2] <= _083_;
  assign { _095_[31:8], _095_[1:0] } = { _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], _095_[7], clk_count[1], 1'h1 };
endmodule
